import type { Product } from "./types";

const ASSET_BASE = "/sites/vn-loccitane-com-1c965340/collections-all-acd0b3f1/images";

export const products: Product[] = [
  {
    slug: "dau-tre-hoa-da-hoa-cuc-truong-sinh",
    sku: "27DH015I22",
    name: "Dầu Trẻ Hóa Da Hoa Cúc Trường Sinh",
    image: `${ASSET_BASE}/product-01-dau-tre-hoa-da-hoa-cuc-truong-sinh.png`,
    volume: "15ml",
    price: "1,790,000₫",
  },
  {
    slug: "gel-tam-huong-hoa-anh-dao-1",
    sku: "24GD500CBR25",
    name: "Gel Tắm Hương Hoa Anh Đào",
    image: `${ASSET_BASE}/product-02-gel-tam-hoa-anh-dao.png`,
    volume: "500ml",
    price: "1,290,000₫",
  },
  {
    slug: "gel-tam-huong-hoa-hong-rose-shower-gel-250ml",
    sku: "24GD250RR25",
    name: "Gel Tắm Hương Hoa Hồng Rose",
    image: `${ASSET_BASE}/product-03-gel-tam-hoa-hong-rose.png`,
    volume: "250ml",
    price: "750,000₫",
  },
  {
    slug: "kem-duong-da-tay-hoa-oai-huong-trang",
    sku: "15MA075LBR25",
    name: "Kem Dưỡng Da Tay Hoa Oải Hương Trắng",
    image: `${ASSET_BASE}/product-04-kem-duong-da-tay-hoa-oai-huong-trang.png`,
    volume: "75ml",
    price: "690,000₫",
  },
  {
    slug: "sua-duong-the-huong-hoa-oai-huong-trang",
    sku: "15LC250LBR25",
    name: "Sữa Dưỡng Thể Hương Hoa Oải Hương Trắng",
    image: `${ASSET_BASE}/product-05-sua-duong-the-hoa-oai-huong-trang.png`,
    volume: "250ml",
    price: "1,090,000₫",
  },
  {
    slug: "gel-tam-huong-hoa-oai-huong-trang",
    sku: "15GD250LBR25",
    name: "Gel Tắm Hương Hoa Oải Hương Trắng",
    image: `${ASSET_BASE}/product-06-gel-tam-hoa-oai-huong-trang.png`,
    volume: "250ml",
    price: "750,000₫",
  },
  {
    slug: "dau-goi-phuc-hoi-toc-hu-ton",
    sku: "11SH500G24",
    name: "Dầu Gội Phục Hồi Tóc Hư Tổn",
    image: `${ASSET_BASE}/product-07-dau-goi-phuc-hoi-toc-hu-ton.png`,
    volume: "500ml",
    price: "1,290,000₫",
  },
  {
    slug: "kem-duong-da-tay-huong-hoa-cuc-huong-ngai",
    sku: "11MA030BAR25",
    name: "Kem Dưỡng Da Tay Hương Hoa Cúc Hương Ngải",
    image: `${ASSET_BASE}/product-08-kem-duong-da-tay-hoa-cuc-huong-ngai.png`,
    volume: "30ml",
    price: "350,000₫",
  },
  {
    slug: "sua-duong-the-hoa-moc-te-mo",
    sku: "11LC250OR25",
    name: "Sữa Dưỡng Thể Hoa Mộc Tê & Mơ",
    image: `${ASSET_BASE}/product-09-sua-duong-the-hoa-moc-te-mo.png`,
    volume: "250ml",
    price: "1,090,000₫",
  },
  {
    slug: "phien-ban-moi-kem-duong-da-tay-hanh-nhan",
    sku: "29MA150A26",
    name: "[Phiên Bản Mới] Kem Dưỡng Da Tay Hạnh Nhân",
    image: `${ASSET_BASE}/product-10-kem-duong-da-tay-hanh-nhan.png`,
    volume: "150ml",
    price: "990,000₫",
  },
  {
    slug: "kem-duong-da-chan",
    sku: "01CP150K26",
    name: "Kem Dưỡng Da Chân",
    image: `${ASSET_BASE}/product-11-kem-duong-da-chan.png`,
    volume: "150ml",
    price: "990,000₫",
  },
  {
    slug: "phien-ban-moi-sua-duong-the-hanh-nhan",
    sku: "29LC240A26",
    name: "[Phiên Bản Mới] Sữa Dưỡng Thể Hạnh Nhân",
    image: `${ASSET_BASE}/product-12-sua-duong-the-hanh-nhan.png`,
    volume: "240ml",
    price: "1,490,000₫",
  },
  {
    slug: "combo-bo-qua-tang10-rose",
    sku: "COMBO10ROSE",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-13-bo-qua-tang-a.png`,
    volume: "Bộ Quà Tặng",
    price: "970,000₫",
  },
  {
    slug: "combo-bo-qua-tang17",
    sku: "COMBO17",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-14-bo-qua-tang-b.png`,
    volume: "Bộ Quà Tặng",
    price: "1,040,000₫",
  },
  {
    slug: "combo-qua-tang-11",
    sku: "COMBO11",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-15-bo-qua-tang-c.png`,
    volume: "Bộ Quà Tặng",
    price: "390,000₫",
  },
  {
    slug: "bo-cham-soc-da-mat-danh-cho-khach-tham-gia-chuong-trinh-big-little-things",
    sku: "BLT-FACE",
    name: "Bộ chăm sóc da mặt dành cho khách tham gia chương trình Big Little Things",
    image: `${ASSET_BASE}/product-16-bo-cham-soc-da-mat-blt.jpg`,
    price: "940,000₫",
    originalPrice: "1,470,000₫",
  },
  {
    slug: "bo-cham-soc-co-the-hanh-nhan-danh-cho-khach-tham-gia-chuong-trinh-big-little-things",
    sku: "BLT-ALMOND",
    name: "Bộ chăm sóc cơ thể hạnh nhân dành cho khách tham gia chương trình Big Little Things",
    image: `${ASSET_BASE}/product-17-bo-cham-soc-co-the-hanh-nhan-blt.jpg`,
    price: "590,000₫",
    originalPrice: "880,000₫",
  },
  {
    slug: "combo-bo-qua-tang-28",
    sku: "COMBO28",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-18-bo-qua-tang-d.png`,
    volume: "Bộ Quà Tặng",
    price: "340,000₫",
  },
  {
    slug: "combo-bo-qua-tang13",
    sku: "COMBO13",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-19-bo-qua-tang-e.png`,
    volume: "Bộ Quà Tặng",
    price: "1,030,000₫",
  },
  {
    slug: "combo-bo-qua-tang12-1",
    sku: "COMBO12",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-20-bo-qua-tang-f.png`,
    volume: "Bộ Quà Tặng",
    price: "1,230,000₫",
  },
  {
    slug: "combo-bo-qua-tang10-1",
    sku: "COMBO10-1",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-21-bo-qua-tang-g.png`,
    volume: "Bộ Quà Tặng",
    price: "970,000₫",
  },
  {
    slug: "combo-qua-tang-8",
    sku: "COMBO8",
    name: "Combo quà tặng 8",
    image: `${ASSET_BASE}/product-22-combo-qua-tang-8.png`,
    price: "680,000₫",
  },
  {
    slug: "combo-bo-qua-tang-21",
    sku: "COMBO21",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-23-bo-qua-tang-h.png`,
    volume: "Bộ Quà Tặng",
    price: "1,010,000₫",
  },
  {
    slug: "combo-bo-qua-tang-45",
    sku: "COMBO45",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-24-bo-qua-tang-i.png`,
    volume: "Bộ Quà Tặng",
    price: "1,120,000₫",
  },
  {
    slug: "combo-qua-tang",
    sku: "COMBOQT",
    name: "Combo Quà Tặng",
    image: `${ASSET_BASE}/product-25-combo-qua-tang.png`,
    price: "390,000₫",
  },
  {
    slug: "combo-bo-qua-tang",
    sku: "COMBOBQT",
    name: "Bộ Quà Tặng",
    image: `${ASSET_BASE}/product-26-bo-qua-tang-j.png`,
    volume: "Bộ Quà Tặng",
    price: "780,000₫",
  },
  {
    slug: "combo-cham-soc-co-the-hanh-nhan",
    sku: "27ALMOND",
    name: "Bộ Sản Phẩm Tẩy Tế Bào Chết Và Dưỡng Da Cơ Thể",
    image: `${ASSET_BASE}/product-27-bo-tay-te-bao-chet.png`,
    price: "2,770,000₫",
  },
  {
    slug: "bo-du-lich-cham-soc-co-the-hanh-nhan",
    sku: "28ALMOND",
    name: "Bộ du lịch chăm sóc cơ thể hạnh nhân",
    image: `${ASSET_BASE}/product-28-bo-du-lich-hanh-nhan.jpg`,
    price: "1,780,000₫",
    originalPrice: "2,070,000₫",
  },
  {
    slug: "bo-doi-goi-xa-cham-soc-toc-l-occitane-tang-bo-cham-soc-co-the-hoa-hong-luoc-go-va-tui-l-occitane",
    sku: "29HAIRSET",
    name: "Bộ đôi gội xả chăm sóc tóc L'Occitane tặng bộ chăm sóc cơ thể hoa hồng, lược gỗ và túi L'Occitane",
    image: `${ASSET_BASE}/product-29-bo-doi-goi-xa.jpg`,
    price: "2,780,000₫",
    originalPrice: "3,460,000₫",
  },
  {
    slug: "tinh-chat-duong-da-dau-ban-dem-tang-bo-cham-soc-toc-va-tui-l-occitane",
    sku: "30SCALP",
    name: "Tinh Chất Dưỡng Da Đầu Ban Đêm tặng bộ chăm sóc tóc và túi L'Occitane",
    image: `${ASSET_BASE}/product-30-tinh-chat-ban-dem.jpg`,
    price: "1,390,000₫",
    originalPrice: "1,680,000₫",
  },
  {
    slug: "tinh-chat-duong-da-dau-cuc-truong-sinh-tang-bo-cham-soc-toc-va-tui-l-occitane",
    sku: "31SCALP",
    name: "Tinh Chất Dưỡng Da Đầu Cúc Trường Sinh tặng bộ chăm sóc tóc và túi L'Occitane",
    image: `${ASSET_BASE}/product-31-tinh-chat-cuc-truong-sinh.jpg`,
    price: "1,590,000₫",
    originalPrice: "1,880,000₫",
  },
  {
    slug: "tinh-chat-tre-hoa-da-cuc-truong-sinh-tang-bo-cham-soc-co-the-hanh-nhan-va-tui-l-occitane",
    sku: "32IMMORTELLE",
    name: "Tinh Chất Trẻ Hóa Da Cúc Trường Sinh tặng bộ chăm sóc cơ thể hạnh nhân và túi L'Occitane",
    image: `${ASSET_BASE}/product-32-tinh-chat-tre-hoa-da.jpg`,
    price: "5,890,000₫",
    originalPrice: "7,070,000₫",
  },
  {
    slug: "kem-duong-chong-lao-hoa-cuc-truong-sinh-tang-bo-cham-soc-co-the-hanh-nhan-va-tui-l-occitane",
    sku: "33IMMORTELLE",
    name: "Kem Dưỡng Chống Lão Hóa Cúc Trường Sinh tặng bộ chăm sóc cơ thể hạnh nhân và túi L'Occitane",
    image: `${ASSET_BASE}/product-33-kem-duong-chong-lao-hoa.jpg`,
    price: "5,490,000₫",
    originalPrice: "6,670,000₫",
  },
  {
    slug: "bo-doi-san-pham-chong-lao-hoa-da-cao-cap-tang-bo-cham-soc-ban-than-tai-nha",
    sku: "34ANTIAGE",
    name: "Bộ đôi sản phẩm chống lão hóa da cao cấp tặng bộ chăm sóc bản thân tại nhà",
    image: `${ASSET_BASE}/product-34-bo-doi-chong-lao-hoa.jpg`,
    price: "11,380,000₫",
    originalPrice: "13,660,000₫",
  },
  {
    slug: "bo-doi-cham-soc-da-mat-cuc-truong-sinh-tang-bo-cham-soc-ban-than-tai-nha",
    sku: "35IMMORTELLE",
    name: "Bộ đôi chăm sóc da mặt cúc trường sinh tặng bộ chăm sóc bản thân tại nhà",
    image: `${ASSET_BASE}/product-35-bo-doi-da-mat-cuc-truong-sinh.jpg`,
    price: "6,380,000₫",
    originalPrice: "8,180,000₫",
  },
  {
    slug: "combo-cham-soc-da-mat-l-occitane-tang-combo-cham-soc-co-the-hanh-nhan",
    sku: "36COMBOFACE",
    name: "Combo chăm sóc da mặt L'Occitane tặng Combo chăm sóc cơ thể hạnh nhân",
    image: `${ASSET_BASE}/product-36-combo-da-mat-hanh-nhan.jpg`,
    price: "8,370,000₫",
    originalPrice: "10,630,000₫",
  },
  {
    slug: "kem-duong-da-cuc-truong-sinh-tang-bo-san-pham-cham-soc-da-cuc-truong-sinh-va-tui-l-occitane",
    sku: "37IMMORTELLE",
    name: "Kem dưỡng da cúc trường sinh tặng bộ sản phẩm chăm sóc da cúc trường sinh và túi L'Occitane",
    image: `${ASSET_BASE}/product-37-kem-duong-cuc-truong-sinh.jpg`,
    price: "3,190,000₫",
    originalPrice: "4,170,000₫",
  },
  {
    slug: "dau-duong-tre-hoa-da-tang-bo-san-pham-duong-da-tre-hoa-cao-cap-tu-cuc-truong-sinh-va-tui-l-occitane-2",
    sku: "38IMMORTELLE",
    name: "Dầu dưỡng trẻ hóa da Tặng Bộ sản phẩm dưỡng da trẻ hóa cao cấp từ Cúc Trường Sinh Và Túi L'Occitane",
    image: `${ASSET_BASE}/product-38-dau-duong-tre-hoa-da.jpg`,
    price: "3,190,000₫",
    originalPrice: "4,020,000₫",
  },
  {
    slug: "tinh-chat-tai-sinh-quyen-nang-ngua-lao-hoa-75ml-tang-bo-doi-cham-soc-da-cuc-truong-sinh-va-tui-l-occitane",
    sku: "39REVITALIFT75",
    name: "Tinh Chất Tái Sinh Quyền Năng, Ngừa Lão Hóa 75ml tặng bộ sản phẩm chăm sóc da cúc trường sinh và túi L'Occitane",
    image: `${ASSET_BASE}/product-39-tinh-chat-75ml.jpg`,
    price: "3,690,000₫",
    originalPrice: "4,560,000₫",
  },
  {
    slug: "tinh-chat-tai-sinh-quyen-nang-ngua-lao-hoa-50ml-tang-bo-doi-cham-soc-da-cuc-truong-sinh-va-tui-l-occitane",
    sku: "40REVITALIFT50",
    name: "Tinh Chất Tái Sinh Quyền Năng, Ngừa Lão Hóa 50ml tặng bộ sản phẩm chăm sóc da cúc trường sinh và túi L'Occitane",
    image: `${ASSET_BASE}/product-40-tinh-chat-50ml.jpg`,
    price: "2,890,000₫",
    originalPrice: "3,760,000₫",
  },
];
